name: Pipeline to run E2E tests

on:
  push:
    branches:
      - master

jobs:

  e2e_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup webapp before run e2e tests
        run: |
          ls -l
          docker compose up -d


      - name: Run e2e tests
        uses: cypress-io/github-action@v6
        with:
          build: npm install
          start: npm run e2e:run

